# dbt_project.yml
name: 'dbt_project'
version: '1.0.0'

# dbt profile
profile: 'dbt_project'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_project:

    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: marts

    analytics:
      +materialized: table
      +schema: analytics
