dbt_project:
  outputs:
    dev:
      type: postgres
      host: postgres_analytics
      user: admin
      pass: admin
      port: 5432
      dbname: warehouse
      schema: staging
      threads: 1
  target: dev
